### ISSUE TITLE
Unable to use Invoke-NSNitroRestApi to do a DELETE operation

### ISSUE THREAD

**Issue by etiennejeanneau** [santiagocardenas/netscaler-configuration#1]
Unable to use Invoke-NSNitroRestApi to do a DELETE operation on a NetScaler.
Ex: Invoke-NSNitroRestApi -NSSession $session -OperationMethod DELETE -ResourceType systemfile -Arguments @{filename="test";filelocation="/var/download/responder"} will return a filename argument missing.

Fix should be simple: treat DELETE the same way GET is treated in the Invoke-NSNitroRestApi commandlet.

**Comment by santiagocardenas** [comment]
Thanks @etiennejeanneau 

 I just submitted a fix to the fix-delete branch. Can you please check it out and let me know if it works as expected? If so, I can merge it into master using #2 

Thanks!
Santiago

**Comment by etiennejeanneau** [comment]
Hi @santiagocardenas, 

I've tested your fix and it does work as expected. Go ahead and merge it into master branch.

Thanks!
Etienne

**Comment by santiagocardenas** [comment]
Great! I've merged the changes. 

Thanks again @etiennejeanneau and feel free to contribute enhancements in the future.
