### ISSUE TITLE
ConvertTo-Json : The maximum depth allowed for serialization is 100

### ISSUE THREAD

**Issue by liamkennedy89** [santiagocardenas/netscaler-configuration#4]
Hey. I'm going through the 'Scripting: Automating NetScaler configurations using NITRO REST API and Powershell' (http://tinyurl.com/jcsc7fa) and  when trying the following line:

Restart-NSAppliance -NSSession $myNSSession -SaveNSConfig -WarmReboot -Wait

I'm getting an error:

ConvertTo-Json : The maximum depth allowed for serialization is 100.
At C:\Users\Liam\Documents\GitHub\netscaler-configuration\Modules\NetScalerConfiguration\NetScalerConf
iguration.psm1:245 char:24
+ ... onPayload = ConvertTo-Json $hashtablePayload -Depth ([int]::MaxValue) ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ConvertTo-Json], InvalidOperationException
    + FullyQualifiedErrorId : ReachedMaximumDepthAllowed,Microsoft.PowerShell.Commands.ConvertToJsonC 
   ommand
 
The variable '$jsonPayload' cannot be retrieved because it has not been set.
At C:\Users\Liam\Documents\GitHub\netscaler-configuration\Modules\NetScalerConfiguration\NetScalerConf
iguration.psm1:260 char:36
+             $restParams.Add("Body",$jsonPayload)
+                                    ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (jsonPayload:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

Netscaler v 11.0
PS v 5.1

Any ideas?

**Comment by santiagocardenas** [comment]
@liamkennedy89

This is due to a new behavior in PowerShell 5.1. I've fixed it in commit 795e7f7

Thanks for finding this!
